services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: |
      pip cache purge
      pip install -r requirements.txt
    startCommand: gunicorn bot:app --bind 0.0.0.0:$PORT
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
    plan: free
    workingDirectory: /opt/render/project/src
